# The Julia Programming Language

Arnav Sood, `arnav.sood@ubc.ca`, UBC R Study Group

In [5]:
using Dates; Dates.format(today(), "e, dd u yyyy")

"Wed, 20 Nov 2019"

## (1/3) Language Overview

### What Julia Is

> Fast

![](benchmarks.svg)

Source: `julialang.org`

In [6]:
function fib(n) # https://github.com/drujensen/fib benchmarks
  if n <= 1 return 1 end
  return fib(n - 1) + fib(n - 2)
end

using BenchmarkTools
@btime fib(46)

┌ Info: Recompiling stale cache file /Users/arnavsood/.julia/compiled/v1.2/BenchmarkTools/ZXPQo.ji for BenchmarkTools [6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf]
└ @ Base loading.jl:1240


  8.072 s (0 allocations: 0 bytes)


2971215073

In [ ]:
; time python3 fib/fib.py 

In [ ]:
; time Rscript fib/fib.r

> Flexible

In [7]:
using Distributions, Measurements

┌ Info: Precompiling Measurements [eff96d63-e80a-5855-80a2-b1b0885c5ab7]
└ @ Base loading.jl:1242


In [11]:
m = 4.71 ± 0.01

4.71 ± 0.01

In [14]:
m = 4.71 ± 0.01 # inspired by Chris Rackauckus' story at JuliaCon about overloading
s = 1.0 ± 0.5

1.0 ± 0.5

In [15]:
d = Normal(m,s)

Normal{Measurement{Float64}}(μ=4.71 ± 0.01, σ=1.0 ± 0.5)

In [16]:
@show mean(d)

mean(d) = 4.71 ± 0.01


4.71 ± 0.01

In [17]:
std(d)

1.0 ± 0.5

In [18]:
var(d) 

1.0 ± 1.0

In [21]:
s^2 - var(d)

0.0 ± 0.0

In [19]:
kurtosis(d)

0.0 ± 0.0

In [20]:
entropy(d)

1.42 ± 0.5

In [24]:
E2 = expectation(Normal(1, 2));

In [25]:
E2(x -> x^2 + 3)

7.999999999999999

In [26]:
using Expectations 

E = expectation(d)
E(x -> x^2)

23.2 ± 1.0

> Simple

From Paul Graham's [accumulator generator](http://www.paulgraham.com/accgen.html):

> The problem: Write a function foo that takes a number n and returns a function that takes a number i, and returns n incremented by i.


In [31]:
foo2 = n -> (i -> i + n)

#16 (generic function with 1 method)

In [32]:
add_by_3 = foo2(3)

#17 (generic function with 1 method)

In [33]:
add_by_3(5)

8

### What Julia Isn't

> The first-best language for every purpose

Statistics Packages: [R Package List](https://cran.r-project.org/web/packages/available_packages_by_name.html)

QuantEcon Data Science: [Why Python?](https://datascience.quantecon.org/introduction/getting_started.html#Why-Python?)

## (2/3) Closer Look

[Expectations.jl](https://github.com/QuantEcon/Expectations.jl)

[Distributions.jl](https://github.com/QuantEcon/Distributions.jl)

In [46]:
methods(lengthen)

# 2 methods for generic function "lengthen":
[1] lengthen(s::String) in Main at In[43]:3
[2] lengthen(n::Int64) in Main at In[43]:2

In [43]:
## Single Dispatch 
lengthen(n::Int) = n + 1
lengthen(s::String) = s * "!"

lengthen (generic function with 2 methods)

In [44]:
lengthen(4)

5

In [45]:
lengthen("studyGroup")

"studyGroup!"

In [48]:
using Expectations

In [50]:
d = Normal()

Normal{Float64}(μ=0.0, σ=1.0)

In [49]:
methods(expectation)

# 12 methods for generic function "expectation":
[1] expectation(dist::Distribution{Univariate,Discrete}) in Expectations at /Users/arnavsood/.julia/packages/Expectations/42bqn/src/iterable.jl:62
[2] expectation(dist::Distribution{Univariate,Discrete}, alg::Type{FiniteDiscrete}; kwargs...) in Expectations at /Users/arnavsood/.julia/packages/Expectations/42bqn/src/iterable.jl:62
[3] expectation(dist::Distribution{Univariate,Continuous}) in Expectations at /Users/arnavsood/.julia/packages/Expectations/42bqn/src/iterable.jl:87
[4] expectation(dist::Distribution{Univariate,Continuous}, alg::Type{#s15} where #s15<:QuadratureAlgorithm; kwargs...) in Expectations at /Users/arnavsood/.julia/packages/Expectations/42bqn/src/iterable.jl:87
[5] expectation(dist::Distribution{Univariate,Continuous}, nodes) in Expectations at /Users/arnavsood/.julia/packages/Expectations/42bqn/src/iterable.jl:224
[6] expectation(dist::Distribution{Univariate,Continuous}, nodes, alg::Type{#s14} where #s14<:ExplicitQuadratureAlgorithm; kwargs...) in Expectations at /Users/arnavsood/.julia/packages/Expectations/42bqn/src/iterable.jl:224
[7] expectation(f::Function, dist::Distribution{Univariate,Discrete}) in Expectations at /Users/arnavsood/.julia/packages/Expectations/42bqn/src/iterable.jl:269
[8] expectation(f::Function, dist::Distribution{Univariate,Discrete}, alg::Type{FiniteDiscrete}; kwargs...) in Expectations at /Users/arnavsood/.julia/packages/Expectations/42bqn/src/iterable.jl:269
[9] expectation(f::Function, dist::Distribution{Univariate,Continuous}) in Expectations at /Users/arnavsood/.julia/packages/Expectations/42bqn/src/iterable.jl:276
[10] expectation(f::Function, dist::Distribution{Univariate,Continuous}, alg::Type{#s14} where #s14<:QuadratureAlgorithm; kwargs...) in Expectations at /Users/arnavsood/.julia/packages/Expectations/42bqn/src/iterable.jl:276
[11] expectation(f::Function, dist::Distribution{Univariate,Continuous}, nodes::AbstractArray) in Expectations at /Users/arnavsood/.julia/packages/Expectations/42bqn/src/iterable.jl:283
[12] expectation(f::Function, dist::Distribution{Univariate,Continuous}, nodes::AbstractArray, alg::Type{#s15} where #s15<:ExplicitQuadratureAlgorithm; kwargs...) in Expectations at /Users/arnavsood/.julia/packages/Expectations/42bqn/src/iterable.jl:283

In [54]:
using LinearAlgebra

In [55]:
M = rand(4, 4)

4×4 Array{Float64,2}:
 0.444178  0.969486   0.789261   0.748211
 0.223644  0.999194   0.0541878  0.905826
 0.89078   0.0944262  0.0157546  0.765882
 0.123715  0.723957   0.844792   0.863236

In [56]:
@which det(M)

det(A::AbstractArray{T,2}) where T in LinearAlgebra at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/LinearAlgebra/src/generic.jl:1341

In [57]:
M = UpperTriangular(M)

4×4 UpperTriangular{Float64,Array{Float64,2}}:
 0.444178  0.969486  0.789261   0.748211
  ⋅        0.999194  0.0541878  0.905826
  ⋅         ⋅        0.0157546  0.765882
  ⋅         ⋅         ⋅         0.863236

In [58]:
@which det(M)

det(A::UpperTriangular) in LinearAlgebra at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/LinearAlgebra/src/triangular.jl:2498

In [59]:
A = rand(4, 4);
M = LowerTriangular(A);

In [62]:
@which M*A

*(A::LinearAlgebra.AbstractTriangular, B::AbstractArray{T,2} where T) in LinearAlgebra at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/LinearAlgebra/src/triangular.jl:1843

## Multiple Dispatch 
[Expectations.jl](https://github.com/QuantEcon/Expectations.jl) # algorithm selection

In [64]:
using Test
f(x) = x + one(x)

f (generic function with 1 method)

In [65]:
f(3)

4

In [66]:
f(3.)

4.0

In [67]:
f([1 1; 1 1])

2×2 Array{Int64,2}:
 2  1
 1  2

In [68]:
@code_native f([1 0; 1 1])

	.section	__TEXT,__text,regular,pure_instructions
; ┌ @ In[64]:2 within `f'
	pushq	%r14
	pushq	%rbx
	subq	$56, %rsp
	movq	%rsi, %rbx
	vxorps	%xmm0, %xmm0, %xmm0
	vmovaps	%xmm0, (%rsp)
	movq	$0, 16(%rsp)
	movq	%rbx, 48(%rsp)
	movabsq	$jl_get_ptls_states_fast, %rax
	callq	*%rax
	movq	%rax, %r14
	movq	$2, (%rsp)
	movq	(%r14), %rax
	movq	%rax, 8(%rsp)
	movq	%rsp, %rax
	movq	%rax, (%r14)
	movq	(%rbx), %rbx
; │┌ @ array.jl:469 within `one'
	movabsq	$_one, %rax
	movl	$1, %edi
	movq	%rbx, %rsi
	callq	*%rax
	movq	%rax, 16(%rsp)
; │└
	movq	%rbx, 32(%rsp)
	movq	%rax, 40(%rsp)
	movabsq	$"+", %rax
	movabsq	$jl_system_image_data, %rdi
	leaq	32(%rsp), %rsi
	movl	$2, %edx
	callq	*%rax
	movq	8(%rsp), %rcx
	movq	%rcx, (%r14)
	addq	$56, %rsp
	popq	%rbx
	popq	%r14
	retq
	nopl	(%rax)
; └


In [69]:
@inferred f(3)
@inferred f(3.)
@inferred f([1 2; 3 4])

2×2 Array{Int64,2}:
 2  2
 3  5

In [72]:
b = 1
g(x) = x + b 

g (generic function with 1 method)

In [76]:
@code_warntype f(2)

Variables
  #self#::Core.Compiler.Const(f, false)
  x::Int64

Body::Int64
1 ─ %1 = Main.one(x)::Core.Compiler.Const(1, false)
│   %2 = (x + %1)::Int64
└──      return %2


In [77]:
@code_warntype g(2)

Variables
  #self#::Core.Compiler.Const(g, false)
  x::Int64

Body::Any
1 ─ %1 = (x + Main.b)::Any
└──      return %1


In [ ]:
@inferred g(4)
@code_native g(3.)

In [78]:
@show 2

2 = 2


2

In [83]:
@test 1 == 1

Test Passed

In [96]:
subtypes(AbstractFloat)

5-element Array{Any,1}:
 BigFloat   
 Float16    
 Float32    
 Float64    
 Measurement

In [102]:
@which (1.0 ± 0.0) + (0.5 ± 0.5)

+(a::Measurement, b::Measurement) in Measurements at /Users/arnavsood/.julia/packages/Measurements/I2ugE/src/math.jl:174

In [101]:
typeof(1.0 ± 0.0) <: AbstractFloat

true

In [98]:
function my_square(n::AbstractFloat)
    print("this is our method")
a    return n^2
end

my_square (generic function with 1 method)

In [99]:
my_square(2.)

this is our method

4.0

In [124]:
a = zeros(Float64, 10)

10-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [127]:
a[4] = "yo"

MethodError: MethodError: Cannot `convert` an object of type String to an object of type Float64
Closest candidates are:
  convert(::Type{T<:Number}, !Matched::T<:Number) where T<:Number at number.jl:6
  convert(::Type{T<:Number}, !Matched::Number) where T<:Number at number.jl:7
  convert(::Type{T<:Number}, !Matched::Base.TwicePrecision) where T<:Number at twiceprecision.jl:250
  ...

In [128]:
a

10-element Array{Float64,1}:
 0.0
 0.0
 0.0
 5.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [109]:
@code_native 2*a

	.section	__TEXT,__text,regular,pure_instructions
; ┌ @ arraymath.jl:52 within `*'
	pushq	%rax
	movabsq	$broadcast, %rax
	callq	*%rax
	popq	%rcx
	retq
	nop
; └


In [110]:
a = zeros(Number, 10)

10-element Array{Number,1}:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0

In [112]:
typeof(a)

Array{Number,1}

In [116]:
struct Foo{T}
    data::T 
end

In [119]:
add_one(foo::Foo{T}) where T = foo.data + one(T)

add_one (generic function with 1 method)

In [120]:
add_one(Foo(2))

3

In [123]:
add_one(Foo(1.0))

add_one(foo::Foo{T}) where T in Main at In[119]:1

In [122]:
methods(add_one)

# 1 method for generic function "add_one":
[1] add_one(foo::Foo{T}) where T in Main at In[119]:1

## (3/3) Scientific Computing

[UBCecon Cluster Tools: Compute Canada](https://github.com/ubcecon/cluster_tools)